In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
# get dimension, property
a.ndim

1

In [6]:
b=  np.array([[1,2,3,4],[4,5,6,7]], dtype = 'int32')
b.ndim

2

In [7]:
b.shape[0]

2

In [8]:
# get dtpe
a.dtype

dtype('int64')

In [9]:
print(b.dtype)

int32


In [10]:
a.itemsize
b.itemsize

4

In [11]:
b.size

8

In [12]:
# get the specific element [r,c]
print(b[1,0])

4


In [13]:
c = np.array([[1,2,3,4,3,4,3],[12,23,12,1,3232,23,233]])

In [14]:
c[1,-3]
c[1,4]

np.int64(3232)

In [15]:
# get specific row or column
# column
c[:,1]

array([ 2, 23])

In [16]:
# entire second row
c[1,:]

array([  12,   23,   12,    1, 3232,   23,  233])

In [17]:
d = c.copy()
d

array([[   1,    2,    3,    4,    3,    4,    3],
       [  12,   23,   12,    1, 3232,   23,  233]])

In [18]:
d [:,1] = [0,0]

In [19]:
d

array([[   1,    0,    3,    4,    3,    4,    3],
       [  12,    0,   12,    1, 3232,   23,  233]])

In [20]:
d[0,:] = [1]

In [21]:
d

array([[   1,    1,    1,    1,    1,    1,    1],
       [  12,    0,   12,    1, 3232,   23,  233]])

In [22]:
c

array([[   1,    2,    3,    4,    3,    4,    3],
       [  12,   23,   12,    1, 3232,   23,  233]])

In [23]:
k = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [24]:
print(k)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# get the specific element:
k[1,0,1]

np.int64(6)

In [26]:
k[0,1,1]

np.int64(4)

In [27]:
k[1,0,:]

array([5, 6])

In [30]:
z = np.zeros((1,3), dtype = 'int16')
z

array([[0, 0, 0]], dtype=int16)

In [31]:
o = np.ones((2,4))

In [32]:
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
f = np.full((1,4),44)
f

array([[44, 44, 44, 44]])

In [34]:
# Random decimal numbers
np.random.rand(2,3)

array([[0.821706  , 0.44007464, 0.98543156],
       [0.33623516, 0.63783761, 0.78875639]])

In [38]:
np.random.randint(50, size = (2,5))

array([[17, 31, 18, 38,  3],
       [44,  7, 48, 44, 24]])

In [48]:
 np.random.randint(-4,9, size = (3,3))

array([[-2,  5,  4],
       [ 0, -1,  5],
       [ 5, -3,  8]])

In [53]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

r2 = np.repeat(arr, 4, axis = 1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [71]:
s = np.ones([5,5], dtype = 'int32')
s

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [74]:
s[1,-2] = 0
s[1,-3] = 0
s[1,-4] = 0

s[-2,1] = 0
s[-3,1] = 0
s[-4,1] = 0
s

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [75]:
s[2,3] = 0
s[3,2] = 0
s[3,3] = 0

s[2,2] = 9

s

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [78]:
h = np.ones((5,5))
h

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
z = np.zeros((3,3))
z
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [81]:
h[1:4, 1:4] =  z
h

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])